name: CI

on:
  push:
    branches: [ main, backend/paullmq8 ]
  pull_request:
    branches: [ main, backend/paullmq8 ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "../../be-career-platform/requirements.txt"
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: pytest
